language: elixir
matrix:
  include:
    - name: "Elixir 1.9 / OTP 22"
      elixir: 1.9
      otp_release: 22.0
    - name: "Elixir 1.8 / OTP 21"
      elixir: 1.8
      otp_release: 21.0
script: MIX_ENV=test mix compile && MIX_ENV=test mix test
